### ISSUE TITLE
Bugs To Fix

### ISSUE THREAD

**Issue by danny248** [InQuest/ThreatKB#115]
- [x] icon to jump to reference link in new tab
- [x] activate blockui on import/extract
- [x] [1:37 PM] Ryan Shipp: threatkb let me add IPs with a non-existent state and they show up on the /c2ips list with that state... it let me add dns with a bad state too, but they didn't show up in the /c2dns list until I added the state on /cfg_states
[1:37 PM] Ryan Shipp: adding the ips/dns through the api
- [x] full page the ui-grids
- [x] add description for ip and dns
- [ ] [2:08 PM] Ryan Shipp: got another state issue, when renaming states on /cfg_state, old c2s are not updated with the new state name, and for c2dns the entries disappear entirely.
[2:09 PM] Ryan Shipp: maybe need some fkey constraints or something there

**Comment by dcuellar322** [comment]
- [ ] fix css of tags

**Comment by dcuellar322** [comment]
I've been adding bad states to c2dns and c2ips via the API and I am not able to reproduce. Either way, I added checks to the create/update methods of c2dns/c2ips to verify the state. If State does not exist, state will be created.

**Comment by dcuellar322** [comment]
I'm not able to reproduce "activate blockui on import/extract", it's working for me.

**Comment by dcuellar322** [comment]
Will await further design for:
[2:08 PM] Ryan Shipp: got another state issue, when renaming states on /cfg_state, old c2s are not updated with the new state name, and for c2dns the entries disappear entirely.
[2:09 PM] Ryan Shipp: maybe need some fkey constraints or something there

**Comment by dcuellar322** [comment]
Opening pull request for those items completed.
