### ISSUE TITLE
Ensure additional reference timestamps are recorded.

### ISSUE THREAD

**Issue by pedramamini** [InQuest/ThreatKB#15]
Comments are one way we can track this. But I'd like this to track reference timestamps as well. This will allow us to build a timeline for each artifact. First seen and by who, then how it spreads.

**Comment by danny248** [comment]
By reference do you mean reference text @pedramamini?

**Comment by pedramamini** [comment]
Wait on this issue actually. I'll have to explain more in person. This is related to the data ingestion portion. Consumed feed items may overlap with existing intel. In such cases, we'll want to simply append the reference to the intel and include the timestamp of when it came in. So if I'm looking at a Yara rule for example, it may have 3 references, each with a timestamp of when it came in.

**Comment by danny248** [comment]
This is handled by #37
