### ISSUE TITLE
macro expansion

### ISSUE THREAD

**Issue by danny248** [InQuest/ThreatKB#182]
* Add a config section for defining macro tags and values.
* Automatically expand those markers on publish.

**Comment by pedramamini** [comment]
Are we skipping this or was it done? Not seeing it.

**Comment by danny248** [comment]
@dcuellar322 ^^

**Comment by danny248** [comment]
This is not done yet

**Comment by dcuellar322** [comment]
@danny248 Done https://github.com/InQuest/ThreatKB/pull/340
