### ISSUE TITLE
(Staging) Tables with small number of items don't display properly

### ISSUE THREAD

**Issue by deadbits** [InQuest/ThreatKB#191]
Built on Ubuntu Linux 16.04 in virtualenv (not running via Docker)
When tables have small number of items you cant view the table contents until you click on a column title, then it comes into view

**before clicking column title**.
<img width="1174" alt="screen shot 2018-02-16 at 7 38 31 pm" src="https://user-images.githubusercontent.com/1332757/36341742-0fe62a26-13c1-11e8-9617-ca717c958db5.png">

**after clicking any column title**
<img width="1170" alt="screen shot 2018-02-16 at 7 52 04 pm" src="https://user-images.githubusercontent.com/1332757/36341750-18047fb4-13c1-11e8-8252-77ab899001c7.png">

**Comment by dcuellar322** [comment]
I really cannot get to reproduce this.

![image](https://user-images.githubusercontent.com/3661852/36941527-fa024e2a-1f22-11e8-97ee-8b7103645f45.png)

I truncated all the data across all my tables and the table displays fine after adding 1 record, 2 records, ...., all the way up to 6 records (which is how it is in your screenshot), etc.

I've tried in Chrome, Safari and Firefox and haven't seen any issues.

**Comment by dcuellar322** [comment]
@deadbits Please pull latest from staging and try again. Not sure what else I can try from my end.

**Comment by danny248** [comment]
Ditto for me here. Tested in firefox, chrome, and safari with 1 signature and task and it was showing up fine.

![image](https://user-images.githubusercontent.com/3219750/36954738-92f7b8b0-1fe9-11e8-93b3-0897b6e9facb.png)

![image](https://user-images.githubusercontent.com/3219750/36954859-5b0f8d46-1fea-11e8-8474-b3976e850296.png)

**Comment by deadbits** [comment]
This may just be my browser or something then - i have no idea. If it works for everyone but me, let's label this one "user-error"

Apologies to have you look into a non-issue
