### ISSUE TITLE
(Staging) Release notes always show the same Modified Signatures

### ISSUE THREAD

**Issue by deadbits** [InQuest/ThreatKB#193]
The screenshot below are the release notes from two separate releases. The Modified Signature shown was not modified in between releases or before either release, although it still shows up as being modified.

<img width="1300" alt="screen shot 2018-02-17 at 9 09 40 am" src="https://user-images.githubusercontent.com/1332757/36341830-5835c10a-13c2-11e8-90e3-2f20769f6e8d.png">

**Comment by deadbits** [comment]
This was a mistake in my workflow. Closing ticket.

**Comment by dcuellar322** [comment]
This should be fixed. Please verify after Pull Request is raised and closed.

**Comment by deadbits** [comment]
Will do. Thanks for digging into this one
