### ISSUE TITLE
(Staging) Category metadata incorrectly mapped on copy/download

### ISSUE THREAD

**Issue by deadbits** [InQuest/ThreatKB#201]
On copy/download of signatures, Metadata is mapped to `File_Characteristics` but on copy/download it appears as `FileCharacteristics`, this should be kept with the underscore left in place

**Comment by deadbits** [comment]
**Reproduction:**
1. Select any Yara signature artifact
    - Click the "Edit" icon and view associated Metadata
2. Click the Copy or Download button
3. Compare metadata keys to original metadata values from the Edit view

The field names in the Edit view show the fields with spaces while the Metadata mappings have them mapped to "Foo_Bar" but on copy or download of a rule the underscores are removed and the spaces as seen on the UI are kept

**Comment by dcuellar322** [comment]
This is my metadata:
![image](https://user-images.githubusercontent.com/3661852/36941620-0c2fa762-1f25-11e8-9387-2bcd995253a1.png)

Selected two yara rules, Copy:
`rule 5 alive
{

	meta:
		File_Characteristics = "5555alive"
		Value With Space = "NA"
		category = "Foo"
		creation_date = "2018-03-03T20:38:36"
		last_revision_date = "2018-03-03T20:38:36"
		name = "5 alive"
		revision = "1"

	strings:
	5 alive
	condition:
	5 alive

}

rule 4more
{

	meta:
		File_Characteristics = "4more"
		Value With Space = "NA"
		category = "Foo"
		creation_date = "2018-03-03T20:38:13"
		last_revision_date = "2018-03-03T20:38:13"
		name = "4more"
		revision = "1"

	strings:
	4more	dfasdf
	condition:
	4more

}

`

![image](https://user-images.githubusercontent.com/3661852/36941625-374132d6-1f25-11e8-972b-edb69a5043ac.png)

`rule 5 alive
{

	meta:
		File_Characteristics = "5555alive"
		Value With Space = "asdfasdfasdfasdfasdfasdf2323"
		category = "Foo"
		creation_date = "2018-03-03T20:38:36"
		last_revision_date = "2018-03-03T20:55:39"
		name = "5 alive"
		revision = "2"

	strings:
	5 alive
	condition:
	5 alive

}`

**Comment by dcuellar322** [comment]
I've also searched the code and cannot find instances where an underscore is replaced.

**Comment by deadbits** [comment]
I've since deleted the screenshots from when I originally filed this but tomorrow morning I'll logon and see if I can get a reproducible case where this happens / if it happens again anyways and post them here.
Thanks for looking into this!

**Comment by deadbits** [comment]
This can be closed, mistake on my side.
