### ISSUE TITLE
Releases modifies Yara signature metadata

### ISSUE THREAD

**Issue by deadbits** [InQuest/ThreatKB#203]
After creating a release, the metadata for the generated Yara signature rule files is changed significantly with some fields being removed completely or fields being changed to different values.
I'm not sure if this bug is in part due to the Metadata mapping settings or the code that creates the Release zip file contents itself

## Imported Signature
```
    meta:
        Author = "InQuest Labs"
        Category = "File Characteristics"
        File_Type = "NA"
        SubCategory1 = "Microsoft"
        SubCategory2 = "Office"
        SubCategory3 = "NA"
        Confidence = "6"
        Creation_Date = "11/29/2017"
        Description = "This signature detects an office document with an embedded VBA project. While this is fairly common it is sometimes used for malicious intent."
        References = "http://msdn.microsoft.com/en-us/library/office/aa201751%28v=office.10%29.aspx"
        Revision = "1"
        Last_Revision_Date = "NA"
        Severity = "0"
        EventID = "2000014"
```

## Exported Signature in Release
```
    meta:
        APSB = "NA"
        CVE = "NA"
        Creation_Date = "NA"
        MSB = "NA"
        Reference = "NA"
        category = "File Characteristics"
        confidence = "NA"
        creation_date = "2017-11-29T00:00:00"
        description = "NA"
        last_revision_date = "2018-02-23T15:14:22"
        name = "FC_Office_Document_with_VBA_Project"
        revision = "1"
        severity = "NA"
```

**Comment by deadbits** [comment]
If more information is needed for this, like the original imported signature artifact versus the resulting Zip file created from the Release please let me know

**Comment by danny248** [comment]
@deadbits can you attach that sig + zip file please?

**Comment by deadbits** [comment]
Yup, I'll email you the signature and release. 

Also just now noticed that the formatting of some strings and conditions are not kept in the Releases based on the originally imported signatures. 
If you want this filed as a different ticket just let me know, though examples of this are present in the current signature and release zip I'm emailing you for this ticket.

For example, an originally imported rule with the formatting of:
```
    strings:
        $magic1 = "foo"
        $blah = "bar"
condition:
    ($magic at 0) and $blah
```

will be returned in the Releases signature file as:
```
    strings:
    $magic1 = "foo"
$blah = "bar"
    conditions:
    ($magic at 0) and $blah
```

**Comment by dcuellar322** [comment]
I deleted ALL of my metadata and then I imported this Yara rule:
```
rule TestExample
{
    meta:
        Author = "InQuest Labs"
        Category = "File Characteristics"
        File_Type = "NA"
        SubCategory1 = "Microsoft"
        SubCategory2 = "Office"
        SubCategory3 = "NA"
        Confidence = "6"
        Creation_Date = "11/29/2017"
        Description = "This signature detects an office document with an embedded VBA project. While this is fairly common it is sometimes used for malicious intent."
        References = "http://msdn.microsoft.com/en-us/library/office/aa201751%28v=office.10%29.aspx"
        Revision = "1"
        Last_Revision_Date = "NA"
        Severity = "0"
        EventID = "2000014"
    strings:
        $foo1 = "foo1"
        $foo2 = "foo2"

        $bar1 = "bar1"
        $bar2 = "bar2"

    condition:
        3 of ($foo*,$bar1,$bar2)
}
```

Then I exported the release and this is how it looks now:
```
rule TestExample
{

	meta:
		category = "File Characteristics"
		creation_date = "2018-03-04T16:17:32"
		last_revision_date = "2018-03-04T16:19:16"
		name = "TestExample"
		revision = "2"

	strings:
	$foo1 = "foo1"
	$foo2 = "foo2"
	$bar1 = "bar1"
	$bar2 = "bar2"
	condition:
	3 of ( $foo* , $bar1 , $bar2 )

}
```

- Metadata keys are now lowercase
- Formatting changes slightly (This doesn't matter)
- Metadata is removed if it doesn't "exist" in the system

I then added ALL of these metadata:
![image](https://user-images.githubusercontent.com/3661852/36951429-53bc4a96-1fc9-11e8-9268-c2d6c8390d75.png)

I then proceeded to import this signature:
```
rule TextExample2
{
    meta:
        Author = "InQuest Labs"
        Category = "File Characteristics"
        File_Type = "NA"
        SubCategory1 = "Microsoft"
        SubCategory2 = "Office"
        SubCategory3 = "NA"
        Confidence = "6"
        Creation_Date = "11/29/2017"
        Description = "This signature detects an office document with an embedded VBA project. While this is fairly common it is sometimes used for malicious intent."
        References = "http://msdn.microsoft.com/en-us/library/office/aa201751%28v=office.10%29.aspx"
        Revision = "1"
        Last_Revision_Date = "NA"
        Severity = "0"
        EventID = "2000014"
    strings:
        $a = "dummy1"
        $b = "dummy2"
        $c = "dummy3"

    condition:
        1 of them /* equivalent to 1 of ($*) */
}
```
Now exported looks like this:
```
rule TextExample2
{

	meta:
		Author = "NA"
		Confidence = "6"
		Description = "This signature detects an office document with an embedded VBA project. While this is fairly common it is sometimes used for malicious intent."
		File_Type = "NA"
		References = "NA"
		Severity = "0"
		SubCategory1 = "Microsoft"
		SubCategory2 = "Office"
		SubCategory3 = "NA"
		category = "File Characteristics"
		creation_date = "2018-03-04T16:33:20"
		last_revision_date = "2018-03-04T16:33:20"
		name = "TextExample2"
		revision = "1"

	strings:
	$a = "dummy1" 
$b = "dummy2" 
$c = "dummy3" 
	condition:
	1 of them

}
```

- Author and References metadata was lost

I deleted the imported Yara rule changing the event id:
```
rule TextExample2
{
    meta:
        Author = "InQuest Labs"
        Category = "File Characteristics"
        File_Type = "NA"
        SubCategory1 = "Microsoft"
        SubCategory2 = "Office"
        SubCategory3 = "NA"
        Confidence = "6"
        Creation_Date = "11/29/2017"
        Description = "This signature detects an office document with an embedded VBA project. While this is fairly common it is sometimes used for malicious intent."
        References = "http://msdn.microsoft.com/en-us/library/office/aa201751%28v=office.10%29.aspx"
        Revision = "1"
        Last_Revision_Date = "NA"
        Severity = "0"
        EventID = "2000015"
    strings:
        $a = "dummy1"
        $b = "dummy2"
        $c = "dummy3"

    condition:
        1 of them /* equivalent to 1 of ($*) */
}
```

This time on the import I made sure that Author and References was in the metadata JSON:
![image](https://user-images.githubusercontent.com/3661852/36951593-36779722-1fcb-11e8-95b1-64114b09a0be.png)

This time on the export:
```
rule TextExample2
{

	meta:
		Author = "InQuest Labs"
		Confidence = "6"
		Description = "This signature detects an office document with an embedded VBA project. While this is fairly common it is sometimes used for malicious intent."
		File_Type = "NA"
		References = "http://msdn.microsoft.com/en-us/library/office/aa201751%28v=office.10%29.aspx"
		Severity = "0"
		SubCategory1 = "Microsoft"
		SubCategory2 = "Office"
		SubCategory3 = "NA"
		category = "File Characteristics"
		creation_date = "2018-03-04T16:39:26"
		last_revision_date = "2018-03-04T16:39:26"
		name = "TextExample2"
		revision = "1"

	strings:
	$a = "dummy1" 
$b = "dummy2" 
$c = "dummy3" 
	condition:
	1 of them

}
```
- Author and References is now there.

I believe things are working as expected.

@danny248 Please review my comment and see if it matches what's expected.

**Comment by deadbits** [comment]
Out of curiosity, why does the formatting of the rules change like we see in the screenshots above after they are copied or from a release? It seems to be arbitrary as to which strings or conditions it decides to un-indent and how far it un-indents them. 

I don’t know that this is a big issue, and the rules still execute properly but for the sake of readability it’s just a bit off compared to the standard Yara syntax.

**Comment by dcuellar322** [comment]
@deadbits Formatting changes due to how the Signature is stripped and parsed as part of Import. It's not "stored" as one long string with formatting and everything.

Each Metadata key and value is parsed and stored, as well as the Strings "string" and Condition "string".

As part of the Copy/Download and Export of a release, ALL the values of the signature are re-stitched together with "new" formatting.

Looks like Newline characters are being maintained but tabs look to be getting stripped.

@danny248 Is it straight forward to leave tabs intact?

**Comment by deadbits** [comment]
Okay, thanks! This makes more sense now. Danny and I were on a call yesterday and explained this all to me as well so I think we're good on the Metadata aspect

**Comment by deadbits** [comment]
Also, Danny opened a new ticket for the whitespace / tab issue under #209 so we can mark this as done too and track that convo there. This original issue filing was mostly a misunderstanding on my end about how data was being mapped in KB and stored from imported rules to their re-assembly.

**Comment by deadbits** [comment]
@danny248 @rshipp @dcuellar322  (wasn't sure who to CC here to get this addressed before prod. release)

We're still seeing this tickets same problem, or at least parts of it.

To summarize:
- Metadata fields from ThreatKB should be in the same exact order and format as the first signature I posted
- Whitespace for metadata, strings, and condition should be preserved so they do not align with their section title names
- Spaces should be removed from after the `{` character to condition, and from the starts of `strings` condition to the beginning on the strings, and from the end of the `condition` content to the ending rule `}`
- Dates should be in the format of MM/DD/YYY, not the full ISO date (if this is possible)
- Revision numbers and Last_Revised_Date should only be updated when a rule has been in a "Released" state and is then edited afterwards, or else everytime a brand new rule is edited before a Release we end up incrementing the Revision information every time - leading to situation where a brand new rule will be labeled as Revision 8 but the Revision Date is the same as the Creation Date (showing that the rule creator simply edited this rule several times _before_ release)

Below is an example of a rule we deploy in the field, with this same formatting, I removed the strings for privacy reasons.
```
rule MC_TrickBot_Spreader
{
    meta:
        Author = "InQuest Labs"
        Category = "Malicious Characteristics"
        File_Type = "EXE"
        SubCategory1 = "Trojan"
        SubCategory2 = "NA"
        SubCategory3 = "NA"
        Confidence = "6"
        Creation_Date = "05/08/2018"
        Description = "This signature detects the LoaderBot malware family capable of credential theft, keylogging, and bitcoin mining."
        References = "REDACATED"
        Revision = "1"
        Last_Revision_Date = "N/A"
        Severity = "6"
        EventID = "XXXXXXXX"
    strings:
        // strings go here
        // redacted due to this being a public forum
    condition:
        uint16(0) == 0x5a4d and
        (3 of ($s*) or 3 of ($x*) and 1 of $(pdb*))
}
```

Now here is a rule I copied from ThreatKB, where the metadata fields are in a completely different order, the dates are not in the correct format, there are several extra metadata fields that aren't in our production rules, and there are extra spaces between the `{` and `meta` and the end of strings and the `condition` field.

Ideally, these two rules would be as identical in metadata formatting as possible or each week during sigpack release we need to spend a good amount of time reformatting every ThreatKB rule to meet the correct format.
```
rule SC_PDF_JavaScript_AsciiHex
{

    meta:
        Author = "InQuest Labs"
        CVE = ""
        Category = "Suspicious Characteristics"
        Confidence = "4"
        Creation_Date = "2018-05-14T14:21:35"
        Description = "This signature detects suspicious PDFs that contains obfuscated JavaScript encoded in Ascii Hex format in its contents."
        EventID = "3000031"
        Exodus = ""
        File_Type = ""
        Last_Revision_Date = "2018-05-21T19:50:23"
        Name = "SC_PDF_JavaScript_AsciiHex"
        PII = ""
        PP = ""
        References = "NA"
        Revision = "4"
        Severity = "4"
        SubCategory1 = ""
        SubCategory2 = ""
        SubCategory3 = ""

    strings:
    //strings go here
    // redacted due to this being a public forum
    condition:
    $magic in (filesize-30 .. filesize) and any of ($re*)

}
```
