### ISSUE TITLE
Word wrap for comments

### ISSUE THREAD

**Issue by deadbits** [InQuest/ThreatKB#204]
If we could get a word wrap for added comments, that'd be 👍 
example below - black blob is a redacted email address :)

<img width="886" alt="upload" src="https://user-images.githubusercontent.com/1332757/36687033-5886332a-1af6-11e8-8a57-fb092a9df8f3.png">

**Comment by dcuellar322** [comment]
@deadbits Fixed. You'll see after Pull Request is raised and closed.
![image](https://user-images.githubusercontent.com/3661852/36942559-d34dc6c0-1f3a-11e8-8f4c-aa5da8759d03.png)

**Comment by deadbits** [comment]
Awesome, thanks!
