### ISSUE TITLE
Not All Results Display Initially

### ISSUE THREAD

**Issue by danny248** [InQuest/ThreatKB#221]
See examples below.

When the initial page for the artifact is rendered, not all results are shown in the UI. The user must click the edit (pencil icon) and then click back to the list for all results to be shown. The table is using ui-grid.

http://ui-grid.info/

**Affected Pages**
http://XYZ.COM/#!/yara_rules
http://XYZ.COM/#!/c2dns
http://XYZ.COM/#!/c2ips

**On First Page Load**
![image](https://user-images.githubusercontent.com/3219750/40926772-aa4c0a02-67e2-11e8-802d-e5884745c2c9.png)

**After Click Edit Icon**
![image](https://user-images.githubusercontent.com/3219750/40926775-ac252642-67e2-11e8-976f-da3939894213.png)

---

**Branch**: `issue/221-not-all-results-display-initially` (PR #222)

**Comment by ofzza** [comment]
Issue should now be fixed for the 3 pages cited as affected, by:
- re-triggering and explicitly setting manually calculated table height
- hiding unneeded horizontal scroll-bars which were adding to the total height
... on data load.

**Comment by ofzza** [comment]
@pedramamini 
This was done, and the PR was merged, but the issue remains ... closing it now!
