### ISSUE TITLE
Resize ui-grid table on full screen

### ISSUE THREAD

**Issue by danny248** [InQuest/ThreatKB#223]
**Branch**: `issue/223-table-width` (PR #225)

**Comment by ofzza** [comment]
@danny248 @pedramamini 

What exactly do you mean by full-screen here? Browser full-screen (which basically just acts as a window resize and seems to work fine here), or is there a "full-screen" option in the app itself that I'm missing?
... please, some more detail?!

Can we agree on a screen-shot (when applicable) and a brief description on top of just an issue name in the future?

**Comment by pedramamini** [comment]
Utilize the full available width in the browser. If the browser window is expanded horizontally, grow with it.

**Comment by ofzza** [comment]
@pedramamini @danny248 
I've made it so that the table (and it's container) will expand to full screen width, up to 1900px (fullHD - scrollbar - margin). With this, there should be enough width for table data, while still not going overboard on extra-wode monitors ...

**Comment by pedramamini** [comment]
Merged.
