### ISSUE TITLE
Add a global search

### ISSUE THREAD

**Issue by rshipp** [InQuest/ThreatKB#227]
Search through all artifacts, all metadata. Search input should be in the main navigation bar.

**Comment by dcuellar322** [comment]
I think It's done, let me know.

https://github.com/InQuest/ThreatKB/pull/314

**Comment by pedramamini** [comment]
@dcuellar322 we wish to additionally search yara_rules.{strings,condition,description,refrences}.

**Comment by pedramamini** [comment]
@dcuellar322 searching of comments as well please.
