### ISSUE TITLE
Left align content in details view.

### ISSUE THREAD

**Issue by pedramamini** [InQuest/ThreatKB#238]
**Branch**: `issue/238-modal-alignment-and-cleanup` (PR #239)

**Comment by ofzza** [comment]
@pedramamini
While working on detail view modals, I'll do some other cleanup ...

- [x] Make section labels consistent - all labels with or without ":" character
- [x] Make modal comments (and similar sections:
  - [x] Show the "Comments" label before the "Add a comment" textarea
![image](https://user-images.githubusercontent.com/4250750/47792098-8d57d800-dd1b-11e8-9fd7-e652d6ed8561.png)
  - [x] Show the "Attached files" label before the "Select or Drop filet" area
![image](https://user-images.githubusercontent.com/4250750/47792373-30105680-dd1c-11e8-8a7a-6ec05ac70c66.png)
  - [x] Only display "See comments" and similar links if/when there is something to see
![image](https://user-images.githubusercontent.com/4250750/47792114-99439a00-dd1b-11e8-8306-7e4d392ef864.png)
- [x] Add a border (same as other inputs) to CodeMirror syntax editors
![image](https://user-images.githubusercontent.com/4250750/47793006-8d58d780-dd1d-11e8-9d16-1d2ca3acd32f.png)
