### ISSUE TITLE
Bootstrap client-side issue due to incompatible versions of angular and ngSanitize

### ISSUE THREAD

**Issue by ofzza** [InQuest/ThreatKB#241]
ngSanitize needs to be updated to same version as main angular module (v1.6.8) - right now it's throwing an error on bootstrap:

https://code.angularjs.org/1.6.8/docs/error/$injector/modulerr?p0=ThreatKB&p1=Error:%20%5B$injector:modulerr%5D%20http:%2F%2Ferrors.angularjs.org%2F1.6.8%2F$injector%2Fmodulerr%3Fp0%3DngSanitize%26p1%3DTypeError%253A%2520q%2520is%2520not%2520a%2520function%250A%2520%2520%2520%2520at%2520B%2520(http%253A%252F%252Fkb.inquest.net%252Flib%252Fangular-sanitize%252Fangular-sanitize.min.js%253A6%253A289)%250A%2520%2520%2520%2520at%2520f%2520(http%253A%252F%252Fkb.inquest.net%252Flib%252Fangular-sanitize%252Fangular-sanitize.min.js%253A6%253A217)%250A%2520%2520%2520%2520at%2520new%2520%253Canonymous%253E%2520(http%253A%252F%252Fkb.inquest.net%252Flib%252Fangular-sanitize%252Fangular-sanitize.min.js%253A13%253A3)%250A%2520%2520%2520%2520at%2520Object.instantiate%2520(http%253A%252F%252Fkb.inquest.net%252Flib%252Fangular%252Fangular.min.js%253A44%253A491)%250A%2520%2520%2520%2520at%2520c%2520(http%253A%252F%252Fkb.inquest.net%252Flib%252Fangular%252Fangular.min.js%253A41%253A413)%250A%2520%2520%2520%2520at%2520Object.provider%2520(http%253A%252F%252Fkb.inquest.net%252Flib%252Fangular%252Fangular.min.js%253A41%253A355)%250A%2520%2520%2520%2520at%2520d%2520(http%253A%252F%252Fkb.inquest.net%252Flib%252Fangular%252Fangular.min.js%253A42%253A279)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Fkb.inquest.net%252Flib%252Fangular%252Fangular.min.js%253A42%253A400%250A%2520%2520%2520%2520at%2520r%2520(http%253A%252F%252Fkb.inquest.net%252Flib%252Fangular%252Fangular.min.js%253A8%253A7)%250A%2520%2520%2520%2520at%2520g%2520(http%253A%252F%252Fkb.inquest.net%252Flib%252Fangular%252Fangular.min.js%253A42%253A180)%0A%20%20%20%20at%20http:%2F%2Fkb.inquest.net%2Flib%2Fangular%2Fangular.min.js:7:76%0A%20%20%20%20at%20http:%2F%2Fkb.inquest.net%2Flib%2Fangular%2Fangular.min.js:43:99%0A%20%20%20%20at%20r%20(http:%2F%2Fkb.inquest.net%2Flib%2Fangular%2Fangular.min.js:8:7)%0A%20%20%20%20at%20g%20(http:%2F%2Fkb.inquest.net%2Flib%2Fangular%2Fangular.min.js:42:180)%0A%20%20%20%20at%20http:%2F%2Fkb.inquest.net%2Flib%2Fangular%2Fangular.min.js:42:364%0A%20%20%20%20at%20r%20(http:%2F%2Fkb.inquest.net%2Flib%2Fangular%2Fangular.min.js:8:7)%0A%20%20%20%20at%20g%20(http:%2F%2Fkb.inquest.net%2Flib%2Fangular%2Fangular.min.js:42:180)%0A%20%20%20%20at%20gb%20(http:%2F%2Fkb.inquest.net%2Flib%2Fangular%2Fangular.min.js:46:250)%0A%20%20%20%20at%20c%20(http:%2F%2Fkb.inquest.net%2Flib%2Fangular%2Fangular.min.js:22:19)%0A%20%20%20%20at%20Uc%20(http:%2F%2Fkb.inquest.net%2Flib%2Fangular%2Fangular.min.js:22:332

https://code.angularjs.org/1.6.8/docs/error/$injector/modulerr?p0=ngSanitize&p1=TypeError:%20q%20is%20not%20a%20function%0A%20%20%20%20at%20B%20(http:%2F%2Fkb.inquest.net%2Flib%2Fangular-sanitize%2Fangular-sanitize.min.js:6:289)%0A%20%20%20%20at%20f%20(http:%2F%2Fkb.inquest.net%2Flib%2Fangular-sanitize%2Fangular-sanitize.min.js:6:217)%0A%20%20%20%20at%20new%20%3Canonymous%3E%20(http:%2F%2Fkb.inquest.net%2Flib%2Fangular-sanitize%2Fangular-sanitize.min.js:13:3)%0A%20%20%20%20at%20Object.instantiate%20(http:%2F%2Fkb.inquest.net%2Flib%2Fangular%2Fangular.min.js:44:491)%0A%20%20%20%20at%20c%20(http:%2F%2Fkb.inquest.net%2Flib%2Fangular%2Fangular.min.js:41:413)%0A%20%20%20%20at%20Object.provider%20(http:%2F%2Fkb.inquest.net%2Flib%2Fangular%2Fangular.min.js:41:355)%0A%20%20%20%20at%20d%20(http:%2F%2Fkb.inquest.net%2Flib%2Fangular%2Fangular.min.js:42:279)%0A%20%20%20%20at%20http:%2F%2Fkb.inquest.net%2Flib%2Fangular%2Fangular.min.js:42:400%0A%20%20%20%20at%20r%20(http:%2F%2Fkb.inquest.net%2Flib%2Fangular%2Fangular.min.js:8:7)%0A%20%20%20%20at%20g%20(http:%2F%2Fkb.inquest.net%2Flib%2Fangular%2Fangular.min.js:42:180

---

**Branch**: `issue/4418-component-registration-on-bootstrap` (PR #242)

**Comment by hoboken515** [comment]
Merged the PR into staging to fix the version discrepancies. Appears to be working as expected now. Closing issue.
