### ISSUE TITLE
Include an auto-updating timestamp field on every table.

### ISSUE THREAD

**Issue by pedramamini** [InQuest/ThreatKB#253]
This will assist us in determining which rows were changed whenever we do manual SQL modifications to the tables.

**Comment by danny248** [comment]
This is already done for all artifacts and most tables actually. See below. Closing this sucker.

Yara Rules: https://github.com/InQuest/ThreatKB/blob/cf3ca1f94c5337e149a1873c457e2f236afb1c91/app/models/yara_rule.py#L22
C2DNS: https://github.com/InQuest/ThreatKB/blob/cf3ca1f94c5337e149a1873c457e2f236afb1c91/app/models/c2dns.py#L20
C2IP: https://github.com/InQuest/ThreatKB/blob/cf3ca1f94c5337e149a1873c457e2f236afb1c91/app/models/c2ip.py#L23

Metadata: https://github.com/InQuest/ThreatKB/blob/cf3ca1f94c5337e149a1873c457e2f236afb1c91/app/models/metadata.py#L23
Metadata_mapping: https://github.com/InQuest/ThreatKB/blob/cf3ca1f94c5337e149a1873c457e2f236afb1c91/app/models/metadata.py#L90
