### ISSUE TITLE
Add single comment to new artifact modals

### ISSUE THREAD

**Issue by danny248** [InQuest/ThreatKB#263]
For ip, dns, and yara rules.

This is so that comments can be added when the artifact is created. The comment should be associated with the new artifact after it is inserted.

**Comment by pedramamini** [comment]
Can we remove these from the new signature creation dialog:

![image](https://user-images.githubusercontent.com/1253573/49849365-2c560200-fda7-11e8-9beb-5c14ce2e1769.png)

**Comment by dcuellar322** [comment]
@danny248 Done. https://github.com/InQuest/ThreatKB/pull/270

![image](https://user-images.githubusercontent.com/3661852/50197920-f49f0b00-030e-11e9-8a3f-366c1127bb44.png)
