### ISSUE TITLE
Filtering negation

### ISSUE THREAD

**Issue by danny248** [InQuest/ThreatKB#276]
Give the user the ability to prefix filter strings with a character to negate it.

EX: {"name":"!foo"} means the filter should return all artifacts where the name does not contain "foo"

**Comment by dcuellar322** [comment]
@danny248 Done. https://github.com/InQuest/ThreatKB/pull/281

Moved filter logic to utility method to reduce all the copy/paste of logic/functionality.

**Comment by pedramamini** [comment]
Can we add a hover state hint in the interface for this?
