### ISSUE TITLE
Add an activity log viewer.

### ISSUE THREAD

**Issue by danny248** [InQuest/ThreatKB#277]
The purpose of this feature is to allow the viewer to glean an overview of non-trivial activities that have occurred over time.

* Artifacts created.
* Artifacts modified.
* Comments added to artifacts.
* Artifacts whose 'state' was toggled on or off a "special" one (Release, Staging, Retired).
* Releases made.

Ideally, we could filter this view by type (comments only for example). Each line item in the activity log should be clickable to the artifact itself. Each activity log should have a user associated with it. Want to be able to filter by the user as well.

**Comment by dcuellar322** [comment]
@danny248 Done! https://github.com/InQuest/ThreatKB/pull/282

Please review as this has a lot of file changes.

Please note the upgraded dependencies in requirements.txt.

**Comment by pedramamini** [comment]
Can we expand out "artifact created" to include the type created? Trying to filter by YARA sigs for example.

**Comment by danny248** [comment]
@dcuellar322 ^^

**Comment by dcuellar322** [comment]
@danny248 Done. https://github.com/InQuest/ThreatKB/pull/326

![image](https://user-images.githubusercontent.com/3661852/54972312-0a991900-4f59-11e9-996d-b8b21a8f6f03.png)

![image](https://user-images.githubusercontent.com/3661852/54972328-1be22580-4f59-11e9-81bb-7afdf84f83f3.png)

![image](https://user-images.githubusercontent.com/3661852/54972337-24d2f700-4f59-11e9-8ca6-ca9d3c951c6d.png)

![image](https://user-images.githubusercontent.com/3661852/54972343-2dc3c880-4f59-11e9-8602-a9e60c50d560.png)

**Comment by pedramamini** [comment]
Looks great thanks!
