### ISSUE TITLE
Copy button returns all undefined.

### ISSUE THREAD

**Issue by pedramamini** [InQuest/ThreatKB#279]
When one or more YARA signature are selected, and the copy action is selected:

![image](https://user-images.githubusercontent.com/1253573/50460630-c8eed700-0945-11e9-86b4-f4b02a4f0405.png)

It's not returning the expected content, instead:

```
undefined

undefined

undefined

undefined

undefined

undefined

undefined

undefined
```

**Comment by dcuellar322** [comment]
Finally fixed. https://github.com/InQuest/ThreatKB/pull/310

Note: ClipboardJS was updated.
