### ISSUE TITLE
Allow for batch change.

### ISSUE THREAD

**Issue by pedramamini** [InQuest/ThreatKB#280]
This is particularly useful in the C2 IP and DNS department, but valuable on the YARA and task pages as well. Want to be able to perform a search/filter, then select all artifacts, and make a mass edit to:

* state (vetting -> released for example), this is the most important.
* tag (APT23 for example)
* owner (want to assign a batch of todos to someone)

**Comment by dcuellar322** [comment]
Done https://github.com/InQuest/ThreatKB/pull/299

Batch Edit activated for 2+ selections on:
- IPs
  - Owner
  - State
  - Tags
- DNS
  - Owner
  - State
  - Tags
- Signatures
  - Owner
  - State
  - Tags
- Tasks
  - Owner
  - State

Note on Tags, obviously only supports Adding tags on batch basis...not removing Tags.

Logic added to prevent duplicates on Tags.

Tagging has been refactored to support bulk operations and reduce DB Operations.

New batch endpoint for each artifact was created.
