### ISSUE TITLE
Check for duplicate YARA sigs by name

### ISSUE THREAD

**Issue by rshipp** [InQuest/ThreatKB#301]
We need YARA sig deduplication by name. #135 seems related, but uses eventid instead of name, and overwrites instead of refusing the import.

When I post one or more YARA sigs to the import endpoint (or use the import page), for any signature that has the same name as an existing signature, I expect the import to act the same as with duplicated IPs/Domains. I.E. refuse to create new sig objects for the given sigs, and return a list of duplicated sigs that were not imported.

**Comment by rshipp** [comment]
This functionality does not appear to work as expected.

On kb:

![image](https://user-images.githubusercontent.com/1382374/54835272-c9221880-4c8f-11e9-9244-b678eb027948.png)

![image](https://user-images.githubusercontent.com/1382374/54835317-da6b2500-4c8f-11e9-93ab-a66403a06bec.png)

Test script:

```python
# depends: pip install threatkb
import threatkb


url = 'http://MYKB/'
token = 'MYTOKEN'
secret_key = 'MYKEY'

state = 'Ingestor'

api = threatkb.ThreatKB(url, token, secret_key, use_https=False)

rule = """
rule Generic_ATMPot {

strings:
	$api1 = "CSCCNG" ascii wide
	$api2 = "CscCngOpen" ascii wide
	$api3 = "CscCngClose" ascii wide
	$string1 = "%d,%02d;" ascii wide
	/*
	0xD:
	.text:004022EC FF 15 20 70 40 00             CALL DWORD PTR DS:[407020]  ; cscwcng.CscCngDispense
	.text:004022F2 F6 C4 80                      TEST AH,80
	winpot:
	.text:004019D4 FF 15 24 60 40 00             CALL DWORD PTR DS:[406024]  ; cscwcng.CscCngDispense
	.text:004019DA F6 C4 80                      TEST AH,80
	*/
	$hex1 = { FF 15 ?? ?? ?? ?? F6 C4 80 }
	/*
	0xD...: 0040506E  25 31 5B 31 2D 34 5D 56 41 4C 3D 25 38 5B 30 2D 39 5D: %1[1-4]VAL=%8[0-9]
	winpot: 0040404D  25 31 5B 30 2D 39 5D 56 41 4C 3D 25 38 5B 30 2D 39 5D: %1[0-9]VAL=%8[0-9]
	*/
	$hex2 = { 25 31 5B ?? 2D ?? 5D 56 41 4C 3D 25 38 5B 30 2D 39 5D }

condition:
	(uint16(0) == 0x5A4D and uint32(uint32(0x3C)) == 0x00004550) and all of them

}
"""

print(api.create('import', {
    'autocommit': 1,
    'import_text': str(rule),
    'shared_reference': 'https://example.com/',
    'shared_state': 'Ingestor',
    'extract_ip': False,
    'extract_dns': False,
}))
```

**Comment by danny248** [comment]
. @dcuellar322 is actively working this one

**Comment by pedramamini** [comment]
For the record, the functionality of rejecting YARA signatures on import based on overlapping rule name should only be enabled if ```ENFORCE_UNIQUE_YARA_RULE_NAMES``` is toggled on via the settings panel.

**Comment by danny248** [comment]
1788a8a9dd075749467292ea385a2abeb973579b
