### ISSUE TITLE
Increment eventid when importing signatures

### ISSUE THREAD

**Issue by rshipp** [InQuest/ThreatKB#303]
When importing 3rd-party sigs that don't have an eventid, via the import page/endpoint, every created sig is assigned the same eventid. The eventid should instead be incremented for each signature successfully created during import, and each sig should receive a different eventid.

**Comment by danny248** [comment]
https://github.com/InQuest/ThreatKB/commit/00cb93f83c250add269c270b817c3b74ec822b68

**Comment by rshipp** [comment]
Verified eventid is incremented as of 2019-02-01.
