### ISSUE TITLE
Convert Revision Display to Yara Rule Form Instead of JSON

### ISSUE THREAD

**Issue by danny248** [InQuest/ThreatKB#311]
![image](https://user-images.githubusercontent.com/3219750/54290086-57075080-4578-11e9-9f5c-a0670e370074.png)

**Comment by danny248** [comment]
Probably best to do this dynamically when the revision is clicked so that we don't bog down the database when opening up the edit menu for the rule

**Comment by dcuellar322** [comment]
Done. https://github.com/InQuest/ThreatKB/pull/313
