### ISSUE TITLE
Add support for defanged IOCs on import.

### ISSUE THREAD

**Issue by pedramamini** [InQuest/ThreatKB#317]
We need to add a preprocessor to the import process to re-fang defanged IPs and domains. Then the regex for domain extraction should work. Alternatively, we can look at using @rshipp's IOCExtractor instead of the regular expressions from IMPORT_DNS_REGEX and IMPORT_IP_REGEX

**Comment by rshipp** [comment]
You could use iocextract for IP extraction, and/or call the `iocextract.refang_ipv4` function independently, but iocextract doesn't support domains at all, so you'd have to build something separate for that.

**Comment by danny248** [comment]
@dcuellar322  this is just a string replace for "[.]" with "." before ingestion

**Comment by dcuellar322** [comment]
@danny248 Done. https://github.com/InQuest/ThreatKB/pull/320

Let me know if that's what you meant

**Comment by rshipp** [comment]
@pedramamini asked me to add a note here on other defang methods. The tables here show some examples: https://iocextract.readthedocs.io/en/latest/#more-details.
