### ISSUE TITLE
Artifact Expiration Field Types

### ISSUE THREAD

**Issue by danny248** [InQuest/ThreatKB#321]
Change timestamp to a be a date picker
Change expiration type to be an enum - only options for the enum as of today will be:

* "date-based"
* "fingerprint-based"

**Comment by pedramamini** [comment]
This is for C2 not YARA signatures. Adjusting the issue title.

**Comment by dcuellar322** [comment]
@danny248 @pedramamini By making expiration type to be an enum with two values. Do we need to be concerned if any existing data has a value NOT in the list of two enum values (fingerprint-based, date-based)?

**Comment by danny248** [comment]
Actually we re-worked this story over the phone. Right now there are 2 columns related to expiration: expiration_timestamp and expiration_type.

We can remove expiration_type and keep expiration_timestamp. Expiration_timestamp should be a date picker in the UI instead of freeform text.

Thats all we need to do for this story. Adam is working on doing the actual expiration based on the timestamp.

**Comment by pedramamini** [comment]
That's correct. We're simplifying ThreatKB expiration to be purely date based. When an artifact is expired, an audit log should be made.

**Comment by dcuellar322** [comment]
Done. https://github.com/InQuest/ThreatKB/pull/337

I'm having slight CSS issue, that I need some assistance on:
![image](https://user-images.githubusercontent.com/3661852/56105278-11380200-5f01-11e9-93c4-9e4d221ce2aa.png)

**Comment by ofzza** [comment]
@dcuellar322 @danny248 
Fixed in branch `issue/321-datepicker-styling` (PR #338)
![image](https://user-images.githubusercontent.com/4250750/56161203-4740b900-5fc9-11e9-83f8-a5077065068f.png)

... I wouldn't consider it the cleanest of fixes, but it works and should work pretty consistently.
