### ISSUE TITLE
Add a new special state for "discarded".

### ISSUE THREAD

**Issue by pedramamini** [InQuest/ThreatKB#331]
Currently, we have three *special* states:

* Release State
* Staging State
* Retired State

I'd like to add a new special state. "Discarded State". Artifacts moved to this state do not appear in the list views and are not accessible to search. They are, in essence, soft deleted.

The use-case here is the following. When we ingest artifacts, if we simply delete the artifact, then it will get reingested as new. If instead, we move ingested artifacts to this discarded state, then a subsequent attempt to ingest it will detect the presence of the artifact in "discarded" state and skip over it.

**Comment by pedramamini** [comment]
@rshipp please add comments / clarifications.
@danny248 @dcuellar322 please prioritize this issue as well.

**Comment by needmorecowbell** [comment]
For right now,  I made an optional discarded state. No new code has been added, just a new state in the database using current features. This is used within python-threatkb currently: https://github.com/InQuest/python-threatkb/blob/yara-functions/threatkb.py#L147

**Comment by pedramamini** [comment]
We decided we'd implement this as active=0, similar to how it's done for YARA artifacts.

**Comment by danny248** [comment]
aae8e9ee614e5f5c2eb9533b006fadbeed1eefcb
