### ISSUE TITLE
UIGrid Rendering Previous Results

### ISSUE THREAD

**Issue by danny248** [InQuest/ThreatKB#332]
#itsBrokenSometimes

**Comment by ofzza** [comment]
Done in branch: `issue/332-debounce-and-clear-search-requests`

Basically 2 changes:
- every new request will cancel any previous requests that might still be pending - this should protect from having requests resolve out of order and user ending up seeing results from a previous search
- every new request will be debounced by 1000ms reducing the number of requests that get fired while user is typing (https://lodash.com/docs/4.17.11#debounce)
