### ISSUE TITLE
Batch task delete

### ISSUE THREAD

**Issue by rshipp** [InQuest/ThreatKB#336]
Can we add batch delete options for tasks?

**Comment by dcuellar322** [comment]
@pedramamini This should be done, can you verify?

**Comment by PhilOrdo** [comment]
Not seeing batch delete at https://threatkb.inquest.net/#!/tasks, only batch edit. No delete options under batch edit either.

**Comment by PhilOrdo** [comment]
Batch delete confirmed to be working.
