### ISSUE TITLE
Batch Edit - Description and Category

### ISSUE THREAD

**Issue by danny248** [InQuest/ThreatKB#347]
Add Description and Category to the Batch Edit functionality

![image](https://user-images.githubusercontent.com/3219750/61498299-606e5280-a988-11e9-8c14-b8f74f38baf2.png)

**Comment by dcuellar322** [comment]
@danny248 Done. https://github.com/InQuest/ThreatKB/pull/348

![image](https://user-images.githubusercontent.com/3661852/61509388-d4722000-a9b3-11e9-8e7a-b5723352e5ab.png)
