### ISSUE TITLE
optional inclusion in release notes generation for categories

### ISSUE THREAD

**Issue by danny248** [InQuest/ThreatKB#353]
Add a flag to the categories that controls whether or not they are included in the release notes changed/added/deleted text.

![image](https://user-images.githubusercontent.com/3219750/65431993-05216c00-dde0-11e9-8c12-669e12c9bae4.png)

**Comment by dcuellar322** [comment]
@danny248 Think I got it done https://github.com/InQuest/ThreatKB/pull/354

**Comment by dspruell-i01** [comment]
Checks out, can verify the new column is present and Release Notes I've reviewed do seem to contain only the selected rule categories.

<img width="1908" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1BPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2e833b3a84151c037ccaffcdcf8c1fef4025febe/image.png" alt="image.png" />

Closing out.
