### ISSUE TITLE
Whitelist is not working.

### ISSUE THREAD

**Issue by pedramamini** [InQuest/ThreatKB#365]
BUG The following whitelist regex was added:

```^microsoft\.com$```

And yet "microsoft.com" was able to be imported. Additionally, can we enumerate / document where whitelist is applied? Is it everywhere? Import, creation, API, etc.

**Comment by pedramamini** [comment]
CIDR block whitelisting also appears to not be functional:

![image](https://user-images.githubusercontent.com/1253573/68143911-15a52600-fef8-11e9-93d8-29f0f7d8014c.png)

![image](https://user-images.githubusercontent.com/1253573/68144295-f9ee4f80-fef8-11e9-8f81-d7cb5ac437a8.png)

**Comment by danny248** [comment]
Fix here: https://github.com/InQuest/ThreatKB/commit/6c6a6963459f2fbb473e4b49825480b7a5d0ddb8
