### ISSUE TITLE
GreyNoise Search Shortcut needs changed

### ISSUE THREAD

**Issue by needmorecowbell** [InQuest/ThreatKB#367]
![image](https://user-images.githubusercontent.com/7833164/68148741-91a86980-ff0a-11e9-9a27-9cf5395957df.png)

The old url is this: https://viz.greynoise.io/ip/<ip>
The new url is: https://viz.greynoise.io/query/?gnql=<ip_or_domain>

**Comment by danny248** [comment]
This can be changed via the ARTIFACT_STATIC_REFERENCES variable in settings. I went ahead and changed to the above and it looks to be woorking.
