### ISSUE TITLE
Revision history diffing.

### ISSUE THREAD

**Issue by pedramamini** [InQuest/ThreatKB#371]
Ideally, we wish to select two different revisions of a YARA signature and visually diff them in the browser. As a stop-gap, the ability to copy the signature body ```rule NAME { ... }``` to the clipboard would allow for a quicker workflow then selecting.

---

**Branch**: `issue/371-diffing-yara-revisions` (PR #372)

**Comment by ofzza** [comment]
Added diffing of revisions:
![image](https://user-images.githubusercontent.com/4250750/70096535-97878c80-1627-11ea-981e-f5a5ca105cc7.png)
