### ISSUE TITLE
Issue when building the docker image

### ISSUE THREAD

**Issue by horialex** [InQuest/ThreatKB#377]
Got an warning when building the docker image

-3.7.4.1 unknown-0.0.0 unknown-0.0.0 virtualenv-20.0.17
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support

**Comment by azazelm3dj3d** [comment]
I'm closing this issue as complete for now, but if you run into this problem again, feel free to re-open the issue.
