### ISSUE TITLE
Add the ability to mass delete files from the yara rule UI (checkbox style)

### ISSUE THREAD

**Issue by danny248** [InQuest/ThreatKB#380]

**Comment by dcuellar322** [comment]
@danny248 Done. https://github.com/InQuest/ThreatKB/pull/384

**Comment by dspruell-i01** [comment]
Not quite sure this is implemented; we don't seem to see a way to select multiple files and mass delete from the file list.

<img width="1308" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2JOQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8b5adefe0b727edd90c4fb51b3d6b18524c4de67/image.png" alt="image.png" />

Screenshot shows no checkbox for multi-select. That said, this is not a critical issue at this time and we'll close it out, just adding a note.
