### ISSUE TITLE
THREATKB CLI/LIB UPGRADES

### ISSUE THREAD

**Issue by pedramamini** [InQuest/ThreatKB#387]
in order:

C2 IP/DNS search by tag
C2 IP/DNS delete by id
C2 IP/DNS create

development in a fashion that this functionality can simply be imported and programmatically interacted with.

**Comment by danny248** [comment]
Completed here: https://github.com/InQuest/ThreatKB/commit/4e8c7d82b540ee10a9447abfe9af73c7fee9fabd
