### ISSUE TITLE
Tags Should be Unique.

### ISSUE THREAD

**Issue by pedramamini** [InQuest/ThreatKB#400]
Notice that the same tag is being created over and over again:

![image](https://user-images.githubusercontent.com/1253573/140176381-0000ce96-ce90-410d-b64c-bff864b24f4a.png)

This is causing the /tags page to never load, as we've built up ~30k tags due to a variety of automation. Once this is fixed, we'll need to do some database cleanup to merge all the tags down into one.

**Comment by dcuellar322** [comment]
@danny248 Fixed

https://github.com/InQuest/ThreatKB/pull/402

Please review logic in DB migration as it includes DB cleanup of duplicate tags. I tested locally with a few records and it's good. But haven't tested with larger volumes.
