### ISSUE TITLE
Drop Down for Descriptions

### ISSUE THREAD

**Issue by WillyMac** [InQuest/ThreatKB#406]

**Comment by pedramamini** [comment]
It would be nice to be able to have a drop downfor the YARA description and allow us to put in generic descriptions in place for various locations ( like macro, xml, bin etc.. )

**Comment by privcloud-danny** [comment]
@WillyMac  do you mean template-style descriptions that would be available here to select from when creating a new sig?

![image](https://user-images.githubusercontent.com/79431870/163837908-f53aefe5-b39b-48da-9062-41161ecaacab.png)

**Comment by WillyMac** [comment]
@privcloud-danny Sorry for the non description in a few of these. Yea that is what we wanted to get into the system as we constantly make rules for Macros for example.   We wanted to be able to select a canned description that we can use instead of writing the same thing over and over again.  

Quick Example for Description for Macros:  This signature detects Microsoft Office macros with XXXX.  While not inherently malicious, threat actors have been known to XXXXXXXX to bypass security controls.
