### ISSUE TITLE
nginx and server gone away error trying to make a pack

### ISSUE THREAD

**Issue by WillyMac** [InQuest/ThreatKB#411]

**Comment by pedramamini** [comment]
![image](https://user-images.githubusercontent.com/1253573/163837743-2064f0ef-aa84-4ae6-9e0e-a03280153bac.png)

**Comment by pedramamini** [comment]
@WillyMac @PhilOrdo is this happening often? i recall this happening after some time, but if we restart all services etc. we got back to normal

**Comment by PhilOrdo** [comment]
seems to only happen after long periods between restarting services
