### ISSUE TITLE
last revision date in the artifacts tables

### ISSUE THREAD

**Issue by vantagepointsecurity-danny** [InQuest/ThreatKB#431]
also sort by last revision by default

**Comment by pedramamini** [comment]
This will get done during "the great reskin" by @ofzza

**Comment by dcuellar322** [comment]
![image.png](https://images.zenhubusercontent.com/64271dd2c2d1e674ff404655/e203c0fd-98fe-4201-8d6c-554e52881618)

**Comment by dcuellar322** [comment]
I've added Revision Date to Signatures page.

**Comment by dcuellar322** [comment]
I've added Revision Date to Signatures page.

**Comment by dcuellar322** [comment]
Or maybe I'm getting confused... what do we mean by Artifacts table? Is this the same issue as

**Comment by dspruell-i01** [comment]
@pedramamini We think this issue was dupe'd by #448, which David closed out with his referenced change (4/16 with screenshot). If these are duplicates, this issue might also be closed. Just wanted to double check and we can close out if so.

**Comment by pedramamini** [comment]
Yep... good to go. Closing out this issue.
