### ISSUE TITLE
docker-compose.yml error (Staging branch)

### ISSUE THREAD

**Issue by mclancy10006** [InQuest/ThreatKB#435]
Error in the docker-compose.yml file. Line 49 shows `- C_FORCE_ROOT=true` and it should be `- C_FORCE_ROOT=1`  when you run the docker build it give and error on this setting.

**Comment by mclancy10006** [comment]
`ERROR: The Compose file './docker-compose.yml' is invalid because:
services.threatkb_agent.environment.C_FORCE_ROOT contains true, which is an invalid type, it should be a string, number, or a null
`

**Comment by danny248** [comment]
Can you give this a shot now @mclancy10006 ?

**Comment by azazelm3dj3d** [comment]
This issue should now be resolved under the [rc branch](https://github.com/InQuest/ThreatKB/tree/rc).
