### ISSUE TITLE
Add last updated date field

### ISSUE THREAD

**Issue by PhilOrdo** [InQuest/ThreatKB#448]
Additional column for last updated date and resize columns to accommodate extra field without looking cluttered.

**Comment by dcuellar322** [comment]
![image.png](https://images.zenhubusercontent.com/64271dd2c2d1e674ff404655/5ae3fb02-0aa4-49ab-ad7b-19a27e7715e2)
This should be done.

**Comment by dspruell-i01** [comment]
@dcuellar322 We believe this one's done, and it's probably a dupe of #431. I'll close this one out here and we'll post a verification out to Pedram on #431 to see if there's still anything outstanding.
