### ISSUE TITLE
Copying a "Released" rule via "edit view" bounces the rule into "Vetting" status

### ISSUE THREAD

**Issue by PhilOrdo** [InQuest/ThreatKB#465]
When looking at a rule in "Released" status with edit view, copying the rule with the "Copy to Clipboard" at the top left will change the status from "Released" to "Vetting". This is similar behavior as modifying a rule in "Released" status.

**Comment by dspruell-i01** [comment]
Question from @dcuellar322 via Slack:

> So this is how the logic says it should behave...
> 
>     if old_state == release_state.state and entity.state == release_state.state and not do_not_bump_revision:
>         entity.state = draft_state.state
> 
> So if the "Old State" (i.e. what the DB reflects) is Released and the "Entity State" (i.e. what is being saved), Then it sets the "Entity State" (what is being saved) to the "Draft State" (i.e. Vetting).
> 
> So I can remove that logic to address the "issue/bug"...
> 
> Or maybe it's expected behavior and the "issue/bug" is closed?

@PhilOrdo can clarify for certain, but this should not be the expected behavior. Copying a rule to clipboard should not change the state of that rule. Fundamentally it doesn't make sense that copying something would result in a change to that object. It seems like we should make sure that the code path that has to do with copying the rule should avoid any unintended effects.

**Comment by dcuellar322** [comment]
We were not able to reproduce, and I can't find logic in the code specific to Copying that would trigger that update/change in State.

We're going to table this, until we can document how to reproduce.

**Comment by WillyMac** [comment]
@dcuellar322 we have found the steps to replicate this bug and posted a video in slack and attached to the bottom of this post

### **Replication steps are the following** 

**- Log into ThreatKB via https://threatkb.inquest.net/#!/login**

<img width="1260" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlpDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bb7aa2e10ad339bbd3dab156c930105f97d00b49/Login.png" alt="Login.png" />


**- Click on the signatures tab** 

<img width="1285" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2RDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--76b6c621038f334b6cee37e6e0a18c2d1a39c8cd/Closesss.png" alt="Closesss.png" />




**- Under the rule name search put the following rule name in :  **FC_Suspicious_File_Name_Segment****
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkJDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4a252b56b72fbda0e76de6fcd9219d7d01a1e99a/RuleName.png" alt="RuleName.png" />


**- Make sure the state of the rule shows as **Released** **( if state in vetting feel free to change to Released for testing)****

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjlDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b5af4928bb5383cf46d4bd78e0a6db78c03301ab/released.png" alt="released.png" />



**- **Click the pencil** on the right side of the rule options to open up the signature editor**

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0pDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f56b3e16113c87efdbb4ec31b47b8ee846c92b95/released_pencil.png" alt="released_pencil.png" />



**- Scroll to the bottom left of the editor and click on **"View Revisions"**** 
<img width="1211" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3BDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c84dd7c95728c19b9e22594c32b491cc89d86ffb/view_revisions_yea.png" alt="view_revisions_yea.png" />



**-  Immediately after the previous step in the upper right of the screen the modal will state **"Successfully saved signature"** _**( this is not supposed to happen as nothing was modified)**_** 
<img width="712" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1JDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3101050680d4d26ad5d1d74bfb1b370f4504e72f/Savewd_Mesasge.png" alt="Savewd_Mesasge.png" />



**- Next click on the close button** 
<img width="1285" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1ZDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a44d4f12bc5d2b0a7efa1a4dcf3f311c87b39f7c/Closesss.png" alt="Closesss.png" />


**- Which will take you back to the Main UI / Rule search section and look at the State and notice it is now changed to **Vetting**.  This is not supposed to happen and the state should be **Released**** 

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkpDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0ca437e803139df99e87fd93ba736f0362126725/RuleName_Vetting.png" alt="RuleName_Vetting.png" />





[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0ZDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--46eda325a95c2079bc2dad5444403f3a36fdf590/State_Change_After_Viewing_Revisions.mov)
