### ISSUE TITLE
Ingested and imported rules without confidence and severity scores cannot be modified.

### ISSUE THREAD

**Issue by PhilOrdo** [InQuest/ThreatKB#486]
The following error occurs when trying to assign an author, confidence and severity to a rule that was imported/ingested the the fields empty. These are required fields when adding a rule manually. This may also cause problems with deleting the rule, as it will still exist in the database after deleting via UI (unable to add a rule with the same name as the system will produce an error stating that a rule with that name already exists).

`Traceback (most recent call last):
  File app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File yara_rules.py", line 482, in update_yara_rule
    rule_state == release_state.state or rule_state == draft_state.state):
AttributeError: 'NoneType' object has no attribute 'state'
'NoneType' object has no attribute 'state'`

**Comment by dspruell-i01** [comment]
Not sure if this issue is related to a new one we just submitted, but noticed the exceptions are different, so noting:
https://app.zenhub.com/workspaces/threatkb-64065b53614cab001cae77c2/issues/zh/16
