### ISSUE TITLE
Dashboard does not load

### ISSUE THREAD

**Issue by PhilOrdo** [InQuest/ThreatKB#488]
Dashboard appears to be broken again. 500 error on version.

<img width="1708" alt="Screenshot 2023-09-18 at 11 39 00 AM" src="https://github.com/InQuest/ThreatKB/assets/48770062/e69f9c8e-0c0e-45c6-9b96-32b297ebc057">

**Comment by azazelm3dj3d** [comment]
This has already been addressed and fixed in the upcoming release. The dashboard should now be loading.
