### ISSUE TITLE
Nuances.

### ISSUE THREAD

**Issue by pedramamini** [InQuest/ThreatKB#58]
@pedramamini 
* ~Go to users, edit one, hit cancel. User list is gone.~ Done
* ~Import functionality seems to hang when you hit "extract" ... need a spinner?~ Done
* ~Same feeling when uploading files. Don't spin too much time on a spinner though, I'm sure @ofzza can whip that one up fast.~ Done
* ~When editing a signature, the required field indicator vanishes. The form can't be submitted until the required fields are filled, but they are no longer marked. Description, reference text and reference link is what I experienced.~ Fixed. The red * will remain even after you type now.
* ~Can't extract artifacts from a list of domains. List of IPs is working, list of domains is failing to be recognized (I wasn't giving the http:// prefix, is that required?)~ The http:// prefix is required otherwise we will get tons of false positives. Another option is to anchor on TLDs. Currently the regex to extract is 'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+'

**Comment by pedramamini** [comment]
* [ ] Can't extract artifacts from:

```

addons-mozilla.download
--
archive-center.com
notification-accountrecovery.com
recovery-customerservice.com
recovery-emailcustomer.com
service-accountrecovery.com
support-aasaam.com
support-accountsrecovery.com
account-support-user.com
account-user-permission-account.com
drive-permission-user-account.com
online-supportaccount.com
goo-gle.bid
goo-gle.mobi
avsupdates.top
account-appleid.ga
apple-iphone.ga
apple-idverify.tk
rnail-service.com
unpeacekeepingonl.com
myicloud-id.com
account-login-com.tk
support-aasaam.bid
goo-gle.bid
goo-gle.cloud
runsscheckmon.com
appleexplorer.info
applepool.org
applewebwallet.com
rapid7pro.com
nordicmail.org
ios-certtificate.com
cloudemail.mobi
smtpserver2.com
runssnetworks.com
support-assaam.bid
microsoft-upgrade.mobi
shape-nato-int.info
accounts-access.com
oauth-dr0pbox.com
account-generator.com
acongresstimes.com
googl.company
appleid-updatesecurity.tk
applescure-idcloud-account.tk
Mmm-Office.eu
thefederalbureauofinvestigation.com
nouvellesfrancaises-2017.com
cadeaux-francais2017.com
iphone-promo-2017.com
mailadmin4.pw
us-apta.org
amazon-accountid.ga
allnews247.ml
apple-accountlockedservicehelp.cf

```

**Comment by pedramamini** [comment]
* [ ] Dropdown is longer than container, must increase the vertical space of container here:
![image](https://user-images.githubusercontent.com/1253573/30124410-b55b1c5c-92fa-11e7-9181-f5713b82da23.png)

**Comment by pedramamini** [comment]
>  Is the delete button supposed to work? If it is, let's definitely have a dialogue confirming it. In our case we'll likely retire sigs to an archive state or something. Delete is useful however, especially when we get to the arbitrary task feature.

* [  ] Scratch the above, it's only a specific one I can't delete: ```maldoc_function_prolog_signature``` Take a look.

**Comment by danny248** [comment]
Closing.
