### ISSUE TITLE
Bug: test running

### ISSUE THREAD

**Issue by danny248** [InQuest/ThreatKB#72]

**Comment by danny248** [comment]
![image](https://user-images.githubusercontent.com/3219750/30552531-dbeeac86-9c63-11e7-8d31-93596d032041.png)

**Comment by dcuellar322** [comment]
@danny248 This is due to the FILE_STORE_PATH config variable not being in the database, needs to be added to cfg_settings and it needs to be Private config entry.

**Comment by danny248** [comment]
https://github.com/InQuest/ThreatKB/pull/76
