### ISSUE TITLE
Need a URL slug that allows users to jump directly to an artifact.

### ISSUE THREAD

**Issue by pedramamini** [InQuest/ThreatKB#89]
So we can paste links to one another.

**Comment by danny248** [comment]
@dcuellar322

**Comment by dcuellar322** [comment]
Added angular routes for:
- /yara_rules/:id
- /c2ips/:id
- /c2dns/:id
- /tasks/:id

Each respective page is loaded followed by the modal opening up for the passed ID.

Should probably create an issue to include a permalink icon that copies permalink to clipboard when clicked.
